### ISSUE TITLE
Expose credit total clearer in Vumi Go

### ISSUE THREAD

**Issue by SteveBarnett** [praekeltfoundation/vumi-go#1096]
Trello card: https://trello.com/c/gmaY6Izo/24-4-0-billing-expose-credit-total-clearer-in-vumi-go

**Comment by hodgestar** [comment]
This happened already too:

![screenshot from 2014-12-12 17 32 50](https://cloud.githubusercontent.com/assets/165551/5414113/f3f07410-8224-11e4-8829-1448c9649c2b.png)
