### ISSUE TITLE
Remove the wizard functionality

### ISSUE THREAD

**Issue by SteveBarnett** [praekeltfoundation/vumi-go#1261]
The dashboard screen has a "New conversation" button that leads to the wizard.

The campaign routing screen has big blue plus buttons for adding a new channel, router, or conversation.

We should remove the button that leads to the wizard, but we need to decide what to replace it with.
1. Nothing.
2. Links to New channel, New router, New conversation.

**Comment by hodgestar** [comment]
I vote for 2.

**Comment by justinvdm** [comment]
+1 on 2

**Comment by SteveBarnett** [comment]
Killing the wizard is in progress: https://github.com/praekelt/vumi-go/pull/1264.

**Comment by SteveBarnett** [comment]
Fixed by #1264
