### ISSUE TITLE
Error: Unexpected end of key/value pairs

### ISSUE THREAD

**Issue by afriapps** [praekeltfoundation/vumi-go#1329]
(ve)$ supervisord -c setup_env/build/go_supervisord.conf

It stops at this step with the error: Error: Unexpected end of key/value pairs

Using Debian 6 64bit

**Comment by hodgestar** [comment]
If looks like one of the supervisord `.conf` files in `setup_env/build` is broken, but I couldn't duplicate this in my local enivornment. If you try `supervisorctl -n -c setup_env/build/go_supervisord.conf` it might print out enough information to figure out which generated file is broken, and then we can try debug this further.

**Comment by hodgestar** [comment]
Closing due to lack of information, but please feel free to add more information and re-open.
