### ISSUE TITLE
Add support for simple outbound API for inbound messages and events.

### ISSUE THREAD

**Issue by hodgestar** [praekeltfoundation/vumi-go#166]
Currently streaming of outbound events is supported. It would be good to have a simple push mechanism for less advanced applications.

**Comment by smn** [comment]
This is already implemented with the `events_url` and the `messages_url` in the HTTP API transport. What's missing is the UI bits for that. If that's the case can we close this and open a new ticket (or combine it with #165)?

**Comment by hodgestar** [comment]
I think we can just close this.
