### ISSUE TITLE
Refactor conversation setup / edit views in frontend-develop into a wizard view plus conversation edit and show screens.

### ISSUE THREAD

**Issue by hodgestar** [praekeltfoundation/vumi-go#336]
The aim is to refactor the existing views into the following screens:
- new conversation screen that allows both:
  - creating a new conversation on a new channel
  - creating a new conversation on an existing keyword routing block
- edit conversation screen
  - that links to add group / contacts screen
  - that links to the show conversation screen
- show conversation screen
  - that has buttons for starting and stopping the conversation

Almost all of these views already exist -- this ticket is mostly about shuffling things around and hooking things up.

**Comment by hodgestar** [comment]
@peterp -- I'm sure I'll be asking a lot of questions as I do this. :)

**Comment by peterp** [comment]
We should do it together!

**Comment by hodgestar** [comment]
:high_brightness: :rainbow: !

**Comment by hodgestar** [comment]
This was completed by @peterp and @jerith in a variety of smaller issue tickets.
