### ISSUE TITLE
Order states on the routing screen by the creation timestamp

### ISSUE THREAD

**Issue by justinvdm** [praekeltfoundation/vumi-go#405]

**Comment by hodgestar** [comment]
This needs #348 to land first so that we can know when channels were checked out (although possibly we can use the new tagpool manager acquisition functionality instead -- either way a bunch of extra work is needed first).

**Comment by hodgestar** [comment]
I think we should change this to rather:
- Split the nodes into connected groups.
- Order the groups by conversation creation time.

We can probably do all of this on the Javascript side if we supply the creation timestamp.

**Comment by hodgestar** [comment]
I'm closing this in favour of #705.
