### ISSUE TITLE
The 'channel' column on the conversation dashboard should show the channels associated with each conversation.

### ISSUE THREAD

**Issue by hodgestar** [praekeltfoundation/vumi-go#492]
Most of the backend work for this was done in #386 and #486.

**Comment by badlard** [comment]
This issue requires new/improved UI that shows not just the channel but the routing block as well. It also needs to account for displaying multiple channels per conversation.

Moving it to 0.5b2

**Comment by hodgestar** [comment]
This column no longer exists and I think we can do without if for now. Let's rather focus on improving the routing display.
