### ISSUE TITLE
On account page, delete 'billing' and 'permissions' sections

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#500]
On the account details page: http://qa-vumi.za.prk-host.net/account/details/ the "admin settings" section should not be displayed.

![screen shot 2013-07-10 at 11 34 30 am](https://f.cloud.github.com/assets/1521387/773820/e16805cc-e943-11e2-974f-a56b49d43481.png)

**Comment by peterp** [comment]
Hmpf. I'm sure I removed this. Is the latest version on?

On Wednesday, July 10, 2013, Ben Adlard wrote:

> On the account details page:
> http://qa-vumi.za.prk-host.net/account/details/ the "admin settings"
> section should not be displayed.
> 
> [image: screen shot 2013-07-10 at 11 34 30 am]https://f.cloud.github.com/assets/1521387/773820/e16805cc-e943-11e2-974f-a56b49d43481.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/praekelt/vumi-go/issues/500
> .

## 

Sent from Gmail Mobile
