### ISSUE TITLE
Remove the "Reports" link from the dashboard

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#507]
@justinvdm isn't going to have diamondash hooked up for 0.5b1, so we need to remove the "Reports" link from the dashboard for now.

![screen shot 2013-07-10 at 4 19 02 pm](https://f.cloud.github.com/assets/1521387/775177/e6918226-e96b-11e2-9d6c-2c2b4c92e581.png)

**Comment by hodgestar** [comment]
I wonder if we shouldn't hook up some of the old reports under reports temporarily?

**Comment by badlard** [comment]
Sure, though only if it's not too much trouble. I'd really like diamondash to get hooked up asap after we deploy 0.5b1
