### ISSUE TITLE
'Dialogue' missing from conversation type drop down

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#529]
The ability to pick 'Dialogue' from the 'conversation type' dropdown on the wizard screen is missing.

![screen shot 2013-07-22 at 10 21 16 am](https://f.cloud.github.com/assets/1521387/833659/e5e8dd5c-f2a7-11e2-80b8-22a4af41da75.png)

**Comment by justinvdm** [comment]
Turned out to be a matter of enabling the app for the dev account on the staging server, closing this issue.
