### ISSUE TITLE
Survey is lost (not saved) when I click 'save' button

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#539]
On the conversation edit page for a dialogue. e.g. http://qa-vumi.za.prk-host.net/conversations/95eb060d51944cc4baff6a4dec182702/edit/
Click the 'save' button
Instead of the survey being saved, I am directed to http://qa-vumi.za.prk-host.net/conversations// and the survey I set up is lost (i.e. it is not saved)

![screen shot 2013-07-24 at 3 29 06 pm](https://f.cloud.github.com/assets/1521387/848625/fd29db88-f464-11e2-9c08-e6d13fd7c0a1.png)

![screen shot 2013-07-24 at 3 29 54 pm](https://f.cloud.github.com/assets/1521387/848627/0c0a7aea-f465-11e2-86a7-bfc654ad530a.png)

**Comment by hodgestar** [comment]
This isn't implemented yet -- it's being worked on in #533.
