### ISSUE TITLE
Channels are not available in Channel drop down

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#590]
- Logged into the dev@praekelt.com account on staging
- On the wizard screen: http://qa-vumi.za.prk-host.net/wizard/create/
- Select "Setup a new channel" radio button
- Try to select a channel from the "Select a channel" drop down
- Only xmpp channels are available. No USSD addresses or SMS long numbers can be selected

Note: no channels are in use (http://qa-vumi.za.prk-host.net/channels/). So this is not an issue of the USSD and SMS channels already in use by other conversations

![screen shot 2013-08-06 at 2 11 17 pm](https://f.cloud.github.com/assets/1521387/916749/25a98780-fe96-11e2-9c1c-8c1d4adc35b6.png)

**Comment by jerith** [comment]
Tags are shared between all users, not just dev@praekelt.com. Maybe someone else is holding them all?

**Comment by jerith** [comment]
I did some digging around on staging. We have four non-XMPP tagpools (sms_longcode_1, sms_longcode_2, ussd_code_1, ussd_code_2) that each have one tag in them and all four of those tags are in use.

**Comment by hodgestar** [comment]
Could we release all tags that are used by accounts that aren't the primary dev one?

**Comment by hodgestar** [comment]
We should also probably display something to the user which explains what is going on (e.g. a false tag in the drop down that says 'None available' or something?

**Comment by jerith** [comment]
If we can find them, yes. We currently lack tools for this kind of thing.

**Comment by jerith** [comment]
I've manually cleared the tags for now. It's possible they're failing to be released somehow, but a quick test released the one I acquired. We can open a new ticket if this happens again.
