### ISSUE TITLE
Can't send bulk message

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#615]
I took the following steps to try and send a bulk SMS
- on the wizard page - added a title, description, picked group message as conversation type, and set up a SMS long number channel
- on the overview (show) page - I added a contact group
- I activated the conversation by clicking the activate btn
- I then clicked on the "Write and send bulk message" btn and got an error message that  the channel I had selected was not able to send SMS messages (see attached screen shot)

However I had selected a SMS long code channel. I had attached a contact group and activated the conversation.

Kashfi is getting calls from Rachel about her inability to send messages. So we need to address this asap.

![screen shot 2013-08-15 at 10 37 27 am](https://f.cloud.github.com/assets/1521387/967767/94377daa-0586-11e3-8ac6-8e9f99cb2dff.png)

**Comment by hodgestar** [comment]
This is a configuration issue in production. Closing this ticket.
