### ISSUE TITLE
Can't activate a dialogue

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#616]
I took the following steps on the production site:
- on the wizard page, defined a title, description, chose 'dialogue' as conversation type, and set up a USSD channel
- I then set up a simple survey on the "survey creator page"
- on the show page I activated the dialogue by clicking the activate btn
- on my dashboard I am then shown a "activating: attempt to stop" button (see screenshot)

The 'activating' status has been persistent since yesterday when I set the conversation up. I tried a new one yesterday night as well which has the same status.

We have a new client who were in the office yesterday, trying to start a dialogue. Please can we get this resolved asap.

![screen shot 2013-08-15 at 10 50 35 am](https://f.cloud.github.com/assets/1521387/967794/ad68461e-0587-11e3-9d3e-d72f09669f29.png)

**Comment by hodgestar** [comment]
Another production config issue.
