### ISSUE TITLE
Released channels not displaying in 'conversation type' dropdown on wizard page

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#617]
I took the following steps:
- released a SMS long code and a USSD number on an individual channel page (e.g. https://go.vumi.org/channels/vumi_starcode%3A%2A120%2A8864%2A108%23/)
- started a new conversation
- on the wizard page, selected "set up a new channel"
- the 'select a channel' drop down is not displaying the channels I just released.

![screen shot 2013-08-15 at 10 57 46 am](https://f.cloud.github.com/assets/1521387/967825/b914ae20-0588-11e3-8f57-c69fd74b15fb.png)

**Comment by jerith** [comment]
This should be fixed when we deploy #622.

**Comment by badlard** [comment]
Fixed!
