### ISSUE TITLE
Clicking on a regular group name shows me all contacts

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#620]
On the contacts page: https://go.vumi.org/contacts/people/
- click on the 'groups' tab in the left hand nav
- click on the name of a 'regular' group
- I am then taken to the whole contact list, instead of just a list of the contacts for that group. (see screenshots)

Note that if you click on the 'smart groups' tab in the left hand nav, and then click on the name of a smart group, only the contacts in that particular group are displayed. This is the correct behavior.

![screen shot 2013-08-15 at 12 05 15 pm](https://f.cloud.github.com/assets/1521387/968066/2b807d50-0592-11e3-8ad5-155da2d0b90b.png)

![screen shot 2013-08-15 at 12 05 25 pm](https://f.cloud.github.com/assets/1521387/968070/3e9bf6ee-0592-11e3-9001-fe094b5f477a.png)

**Comment by justinvdm** [comment]
Solved in #618
