### ISSUE TITLE
Can't get past the first dialogue screen when running dialogue over SMS

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#654]
I took the following steps:
- set up a dialogue over an SMS long number
- assigned a group called 'Ben' that contained just my contact info to the dialogue
- activated the conversation
- received SMS of the first question 
- responded with an answer choice
- received SMS of the first question again
- responded with a different answer choice
- received an SMS of the first question again
- responded with a different answer choice
- received an SMS of the first question again

For some reason I am not able to move past the first screen.

This was reported by Eve at Afropinions - so we have a client behind the request.

**Comment by smn** [comment]
Can you perhaps paste a screenshot of the messages sent & received?

**Comment by badlard** [comment]
Eve and I were responding with the actual answer text and not the answer number. This is not a bug but a UX issue.
