### ISSUE TITLE
Where should we have lunch?

### ISSUE THREAD

**Issue by hodgestar** [praekeltfoundation/vumi-go#667]
Possible options:
- [ ] Jamaica Me Crazy
- [x] Banana Jam
- [ ] Knead in Muizenberg
- [ ] Empire

Please add your own options above if you like.

**Comment by smn** [comment]
Anywhere with decent beer, banana milkshakes, rock shandys or americanos.

**Comment by justinvdm** [comment]
:+1: on any of the current options :)

**Comment by badlard** [comment]
Banana Jam works well for me. 12 pm ok with everyone? I need to get the car back by 1:40

**Comment by smn** [comment]
Which day is this again?

**Comment by smn** [comment]
Ah tomorrow.

**Comment by hodgestar** [comment]
Banana Jam, 12pm it is, I think. See you all there!

**Comment by hodgestar** [comment]
Nom.
