### ISSUE TITLE
Move contact and group management to the Go HTTP API

### ISSUE THREAD

**Issue by justinvdm** [praekeltfoundation/vumi-go#668]

**Comment by justinvdm** [comment]
As mentioned in #633 for the case of importing contacts, we need better validation feedback in the UI. The current way things are structured makes error reporting difficult. The restructuring necessary for moving contact management to the HTTP API will hopefully involve the changes that will make this error reporting easier.

**Comment by badlard** [comment]
#677 is related to this issue

**Comment by hodgestar** [comment]
We should try include migrating the API from JSON RPC to REST into this set of work (although possibly in a different PR).

**Comment by badlard** [comment]
Now superseded by the contacts API
