### ISSUE TITLE
Inbox search returns a 500

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#682]
I took the following steps:
- on a message inbox screen: e.g. https://go.vumi.org/conversations/18b5f81784dc42dfb0d972a1ac126982/message_list/
- in the search box, I search for a word that I know a user has responded. In my case "cornia"
- I click the 'search' button
- I get a 500

![screen shot 2013-09-02 at 11 51 41 am](https://f.cloud.github.com/assets/1521387/1066490/58bd45b0-13b5-11e3-8e6b-0e8bea5d0970.png)

**Comment by jerith** [comment]
There are two tests in #393 that are broken in confusing ways, almost certainly related to this.

**Comment by hodgestar** [comment]
I think this is the same as #675 but let's leave both open for now.

**Comment by hodgestar** [comment]
Closing this as a duplicate.
