### ISSUE TITLE
Factor out the common action classes used by conversations, routers and channels.

### ISSUE THREAD

**Issue by hodgestar** [praekeltfoundation/vumi-go#688]
Currently lots of the files under `go/base/static/js/src/{conversation,router,channel}/` are essentially identical except for some minor textual differences. We should factor these out so they all use the same code.

**Comment by justinvdm** [comment]
We definitely need some refactoring here, but I'm wondering how useful it will be, since the plan is to get rid of these action views and things related to `TableFormView` all together when we can invoke actions as calls to our http api.

**Comment by hodgestar** [comment]
Good point. Closing this for now.
