### ISSUE TITLE
Add ability to export all contacts or all contacts in a group back to the UI

### ISSUE THREAD

**Issue by hodgestar** [praekeltfoundation/vumi-go#699]
We appear to have lost it when the new UI was introduced.

**Comment by justinvdm** [comment]
I'm probably missing something, but we seem to have this in the new UI. We check the head checkbox to select all the contacts (although it will only select contacts up to the page limitation we are using). Are you maybe talking about that?

**Comment by hodgestar** [comment]
I mean _all_ contacts, not all contacts on the page.

**Comment by justinvdm** [comment]
@hodgestar Ah ok cool. In that case, I'm wondering if it makes sense to do this as one of the steps during moving contacts to the HTTP API (depending on how important it is do this immediately)? I'm just not sure if it makes sense to add code to a place that isn't going to exist for much longer (not in its current form, at least). That said, I'm still okay with us doing it now, and would be happy to tackle this if it would make things easier on you.

**Comment by hodgestar** [comment]
I think we need this now rather than later. Maybe a quick solution is just to add an extra button that says "Export All" and link that up? We probably need the button in a few places (i.e. all contacts, groups and smart groups).

**Comment by smn** [comment]
The groups listing also has an "Export" button -- won't that export all
contacts in the group?

On 9 September 2013 13:33, Simon Cross notifications@github.com wrote:

> I think we need this now rather than later. Maybe a quick solution is just
> to add an extra button that says "Export All" and link that up? We probably
> need the button in a few places (i.e. all contacts, groups and smart
> groups).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/praekelt/vumi-go/issues/699#issuecomment-24065712
> .

## 

Simon de Haan | Chief Engineer Praekelt Foundation

praekeltfoundation.org | praekelt.com
M: +27 (0) 76 449 3806  |  http://twitter.com/smn

**Comment by justinvdm** [comment]
Cool, will add an "Export All" button. The group pages don't need it, I don't think, since they have the "With group:" buttons, "Export" being one of them.

**Comment by justinvdm** [comment]
@hodgestar @badlard I think that the action buttons at the top of all our 'table-like' views aren't really working too well in terms of usability, and we keep needing to add more and more buttons (like "Export All" in this case). I think we should make a point of getting some UX advice for the actions in these views. One idea I had (although there is probably something much better):

![suggestion](https://f.cloud.github.com/assets/1731223/1106527/ae69f502-1947-11e3-86de-63402b4e77a6.png)

**Comment by hodgestar** [comment]
On Mon, Sep 9, 2013 at 1:46 PM, Simon de Haan notifications@github.com wrote:

> The groups listing also has an "Export" button -- won't that export all
> contacts in the group?

That's a good work around for now. Still +1 on "Export All" on the
contacts listings.

**Comment by hodgestar** [comment]
Closing this -- we need to generally improve the way action buttons look and that's coming in a separate ticket.
