### ISSUE TITLE
Surveys not accepting upper case responses

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#723]
If I run an old survey
I list upper case and lower case letters as valid 
However if I respond with an upper case letter then I am not moved on to the next question
Instead the first question is presented again

Eve is running old surveys, as she is waiting for #714 to be fixed before she uses dialogues.

**Comment by hodgestar** [comment]
Does unchecking the "Are the valid responses for each question case sensitive?"  solve the problem?

**Comment by badlard** [comment]
Ah - I missed that. That solves it. Thanks.
