### ISSUE TITLE
Deploys leave jsbox application hung

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/vumi-go#742]
This issue keeps recurring after deploys, leaving JS applications in a hung state which requires dev team intervention to exit from. Logs show `/var/praekelt/vumi-go/ve/bin/python: can't open file '/var/praekelt/vumi-go/ve/src/vumi/vumi/application/sandbox_rlimiter.pyc': [Errno 2] No such file or directory`

**Comment by hodgestar** [comment]
This is being addressed in praekelt/vumi#630.
