### ISSUE TITLE
Credit cost not displaying

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#778]
On the message cost admin page: http://qa-vumi.za.prk-host.net/admin/billing/messagecost/

The credit cost is not displayed. Also a note that the credit factor should be 25 (1/.04)

![screen shot 2013-11-18 at 12 17 28 pm](https://f.cloud.github.com/assets/1521387/1561790/de323860-503a-11e3-8997-35deb9c05dea.png)

**Comment by andreit** [comment]
I think there is a problem with the `credit_cost` calculation. Does that mean that 1 cent in base currency gives us 25 credits?

**Comment by badlard** [comment]
One credit is 4 US cents ($.04). So, one 1 US cent gives 1/4 credit. Vumi Go's currency is US dollars only.

**Comment by andreit** [comment]
Just to confirm the credit calculations. So if my message cost is .001 cents and my markup is 20.0% i get a resulting message price of 0.0012 cents. Then using a credit conversion factor of 0.25 I get a message cost of 0.000300 credits. Is that correct? If I quantize that cost to 3 decimal places we end up with a message cost of 0.000... should we store up to 6 decimal places?

**Comment by badlard** [comment]
Good point. When entering the .001 cost I am not going to include a markup (the .001 price already includes sufficient margin). So three decimal places is sufficient.

**Comment by hodgestar** [comment]
I wondering if we shouldn't drastically up the precision anyway, just to avoid skirting the precision boundary constantly? Either way it might be worthwhile checking that things don't end up as zero if they weren't before (the fancy way to do this is to pass `traps=[Underflow, ...]` to the Decimal constructor but I'm not sure how easy Django makes that -- see http://docs.python.org/2/library/decimal.html).

**Comment by andreit** [comment]
Even without the markup (0.001 \* 0.25 = 0.00025). I will set the precision to 6 decimal places and look into the `traps` parameter of `quantize`.

**Comment by andreit** [comment]
This bug will get implicitly resolved by #777

**Comment by hodgestar** [comment]
Closing this since #777 is well under way and the two issues are essentially duplicates (different symptom, same problem).
