### ISSUE TITLE
Can't search for contacts by msisdn 

### ISSUE THREAD

**Issue by vgeddes** [praekeltfoundation/vumi-go#827]
In the Go UI, it is not possible to search for contacts by a full or partial msisdn.

**Comment by smn** [comment]
- `msisdn:\+2776449*`
- `msisdn:'+27764493806'`

**Comment by vgeddes** [comment]
That search syntax was not immediately apparent. I was under the impression that the high-level contact search would just match on all fields using a simple substring regex, as in many other webapp search UIs. Do you mind if I reopen and retitle appropriately?

**Comment by vgeddes** [comment]
Err, what I mean is, we should probably add a little Help bubble to the UI pointing out the syntax.

**Comment by smn** [comment]
I think https://github.com/praekelt/vumi-go/issues/694 covers that?

**Comment by hodgestar** [comment]
#771 covers adding help text.
