### ISSUE TITLE
Provide means of normalizing MSISDNs from inside jsbox.

### ISSUE THREAD

**Issue by smn** [praekeltfoundation/vumi-go#829]
To prevent home grow normalisations happening in Javascript land.

**Comment by hodgestar** [comment]
Maybe this should be implemented in the sandbox toolkit?

**Comment by smn** [comment]
Possibly, main motivation was that we already have code for it in Python land and the sandbox code I came across needing this was:

``` javascript
function InternationalNumber(msisdn) {
    if (msisdn[0] == '0') {
        msisdn = '27' + msisdn.substring(1)
    }
    return msisdn
}
```

**Comment by hodgestar** [comment]
I'm closing this in favour of praekelt/vumi-jssandbox-toolkit#192.
