### ISSUE TITLE
Test http_request_full() timeout

### ISSUE THREAD

**Issue by jerith** [praekeltfoundation/vumi-go#845]
From @smn's comment on praekelt/vumi-wikipedia#37.

**Comment by jerith** [comment]
Turns out this is quite hard to do. We can't just pass in a fake reactor because we need a bunch of functionality from the real one to make the HTTP calls.

Since we already test this with (short) real timeouts, I'm closing the ticket.

**Comment by smn** [comment]
ok, I'll take your word for it.
