### ISSUE TITLE
Sphinx docs for KeyValue store resource are incomplete.

### ISSUE THREAD

**Issue by smn** [praekeltfoundation/vumi-go#847]
For some reason the various `handler_*` methods aren't automatically included.

https://vumi-go.readthedocs.org/en/latest/sandbox-resources.html#vumi.application.sandbox.RedisResource

**Comment by hodgestar** [comment]
This is because the `handler_*` methods aren't documented (but they'll need to be document in vumi itself).

**Comment by hodgestar** [comment]
Closing this since it'll be addressed by praekelt/vumi#719.

**Comment by smn** [comment]
oh right, that's vumi, thanks.
