### ISSUE TITLE
Enable CSV export of Vumi Go user details

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#880]
In /admin (https://go.vumi.org/admin/base/gouser/) enable a way to download user details as a CSV.

Suggested UI is attached.

![screen shot 2014-02-24 at 10 25 56 am](https://f.cloud.github.com/assets/1521387/2243524/7a68bc42-9d2d-11e3-80ee-396d8eab4ee7.png)

**Comment by badlard** [comment]
@hodgestar I copied and pasted the user list into Excel. Going to close the ticket as it's no longer a requirement i.m.o.

**Comment by hodgestar** [comment]
Cool.
