### ISSUE TITLE
Streaming HTTP API don't allow specifying of metrics store.

### ISSUE THREAD

**Issue by smn** [praekeltfoundation/vumi-go#896]
Currently default to `default`.

**Comment by smn** [comment]
oops code for this got attached to #848.

**Comment by hodgestar** [comment]
@smn Should this have been closed now that #848 has landed?

**Comment by smn** [comment]
let's leave it open as apparently the streaming API still doesn't allow one to set it.

**Comment by smn** [comment]
updated the ticket title to mention streaming api.

**Comment by smn** [comment]
Yeah duplicate of #905 closing.
