### ISSUE TITLE
Not giving a `config` key for config 500 errors not warns

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/vumi-go#965]

**Comment by hodgestar** [comment]
@imsickofmaps Do you remember what this issue was about? Was it jsbox related?

**Comment by imsickofmaps** [comment]
@hodgestar yes - starting a new conversation of that type didn't give you any bootstrapped setup for you to fill and just broke with no error if you forgot config

**Comment by hodgestar** [comment]
Cool, so this should be addressed by the new ticket. :)

**Comment by imsickofmaps** [comment]
@hodgestar closing because addressed by #1032
