### ISSUE TITLE
Contacts API prototype

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#968]
Functional requirement from Mike: pass a contact key in, update field, and pass contact back

Plan:
- [x] Split out the Toolkit and create repo for contacts store API
- [x] Reuse store API commands - 'get' and 'update'. Maybe 'create' and 'delete' if time allows.
- [x] For authorization - make the bouncer read a configuration file

**Comment by hodgestar** [comment]
This now exists in http://github.com/praekelt/go-contacts-api.

**Comment by badlard** [comment]
Success!
