### ISSUE TITLE
Text in Sandbox Logs is not wrapping

### ISSUE THREAD

**Issue by emilesilvis** [praekeltfoundation/vumi-go#996]
Text in Sandbox Logs is not wrapping.

![vumi go](https://cloud.githubusercontent.com/assets/557338/3690935/5bd34996-134d-11e4-9cf4-f9237917e8ec.png)

**Comment by SteveBarnett** [comment]
Add { word-break: break-all; } ?

**Comment by emilesilvis** [comment]
Yeah, probably an easy thing to fix. Don't think it's a priority though.
